classDiagram 
    class Artiste{
        Artiste : +string cin
        Artiste : +string name
        Artiste : +string birthdate
        Artiste : +string genre
        Artiste : +string country
        Artiste : +string city
  
    }